# Generated by Django 4.2.6 on 2023-12-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
