# Generated by Django 4.2.6 on 2023-10-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Все', max_length=100, unique=True),
        ),
    ]
