# Generated by Django 4.2.6 on 2023-10-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner', '0002_category_latin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='latin_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
