# Generated by Django 4.2.6 on 2023-10-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner', '0003_alter_category_latin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
