# Generated by Django 4.2.6 on 2023-10-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
