# Generated by Django 4.2.6 on 2023-10-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
    ]
