# Generated by Django 4.2.6 on 2023-11-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner', '0007_subtask_delete_usertimezone_task_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='subtask',
            new_name='title',
        ),
    ]
