# Generated by Django 4.2.6 on 2023-11-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner', '0008_rename_subtask_subtask_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
