# Generated by Django 4.2.6 on 2023-11-14 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note_planner', '0010_task_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskColorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.IntegerField(max_length=256)),
                ('green', models.IntegerField(max_length=256)),
                ('blue', models.IntegerField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
