# Generated by Django 4.2.6 on 2023-11-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner', '0011_taskcolorsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcolorsettings',
            name='blue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='taskcolorsettings',
            name='green',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='taskcolorsettings',
            name='red',
            field=models.IntegerField(),
        ),
    ]
