# Generated by Django 4.2.6 on 2023-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner', '0012_alter_taskcolorsettings_blue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcolorsettings',
            name='blue',
        ),
        migrations.RemoveField(
            model_name='taskcolorsettings',
            name='green',
        ),
        migrations.RemoveField(
            model_name='taskcolorsettings',
            name='red',
        ),
        migrations.AddField(
            model_name='taskcolorsettings',
            name='high_priority_color',
            field=models.CharField(default='#440673', max_length=20),
        ),
        migrations.AddField(
            model_name='taskcolorsettings',
            name='low_priority_color',
            field=models.CharField(default='#383838', max_length=20),
        ),
        migrations.AddField(
            model_name='taskcolorsettings',
            name='medium_priority_color',
            field=models.CharField(default='#06734b', max_length=20),
        ),
    ]
