# Generated by Django 4.2.6 on 2023-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner', '0016_userprofileinfo_load_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='maid_photo',
            field=models.BooleanField(default=False),
        ),
    ]
