# Generated by Django 4.2.6 on 2023-12-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner', '0017_userprofileinfo_maid_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='maid_photo',
            new_name='main_photo',
        ),
    ]
