# Generated by Django 4.2.6 on 2023-12-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_planner', '0022_alter_usercharts_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCharts',
        ),
    ]
